apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
    - name: kafka-port
      port: 19093
      protocol: TCP
      targetPort: 19093
  selector:
    app: kafka
  type: NodePort